### ISSUE TITLE
ZONE_HIGHMEM

### ISSUE THREAD

**Issue by Limaomao821** [kernelrookie/KernelDoc#3]
# 32位X86中使用的高端内存概念
按照我的理解，高端内存解决的问题是：如何访问没有固定映射到内核地址空间的物理内存（4GB物理内存，进程占0-3GB，内核3-4GB）。
对于64位X86来说，内核的虚拟地址空间会映射到物理内存顶部的64T空间。足够大，广泛使用的计算机的物理内存不太可能超过这个值，也就是物理内存可以全部映射到内核地址空间中。

针对上面两句话，问题：
1. 如果没有高端内存，32位X86访问非0-3GB的地址空间会有什么问题？
2. 如果物理内存小于内核地址空间，这时内核地址空间是如何映射到内核地址空间的？

谢谢

**Comment by Martins3** [comment]
为什么要使用 highmem, 因为kernel virt address space 和 user virt address space 不可以交错（不然会导致用户态和内核态切换的时候，TLB 的 flush[^1]) 并且加起来大于物理地址的时候。

所以没有高端内存的时候，一种方法是放弃 内核和用户的虚拟地址空间不能交错的约束。

物理内存小于内核地址空间的情况，注意，在 64 bit 空间的时候，物理内存就是小于内核地址空间的。只是初始化填充内核映射页表的时候，映射只有物理地址的部分。
[^1]: https://lwn.net/Articles/813201/

**Comment by Limaomao821** [comment]
关于高端内存，我认为得从两个方面去认识：
1. 高端内存最初是什么？
+ 32位X86的地址空间4GB，PAE可以使得X86使用2^36的地址空间，PAE带来的超过4GB的物理内存，是不会一直映射到进程或者操作系统的4GB地址空间之内的，也就是常说的“cannot permamently mapped"。这是高端内存最初的含义
2. 高端内存的演化
+ 为了减小TLB flush造成的性能损失，将整个虚地址空间按3：1划分成kernel space和user space。那么这个时候，我们相当于是将内核地址空间变成2^10大小，超出2^10大小的内存，内核是无法直接访问的（"cannot permamently mapped"）。

我感觉很多博客书本什么的，将高端内存相关的东西杂揉在一起说，很不容易理解。最好的材料是[Robert Love在Quora上面的回答](https://qr.ae/pNsEKJ)。不过博客书本什么的还是得看看，给你带来困惑，看Robert写的东西才会恍然大悟。

**Comment by Martins3** [comment]
> 将内核地址空间变成2^10大小，超出2^10大小的内存
`2^10` 是什么意思 ?

highmem 的存在的原因是，内核的虚拟地址空间没有办法那么多的物理地址，此处映射的含义是，建立 内核虚拟地址和 物理地址之间的 页表，从而可以 page walk，访问。

其实这里有一个问题，那就是为什么内核需要访问整个物理空间，蜷缩在自己的内核地址空间线性映射的物理地址空间不就可以了，可以检查一下 kmap/ kmap_atomic 的调用位置，就大致可以知道。

可以观察一下 kmap 函数在 highmem 和 非highmem 的情况下的实现的差别，没有 highmem 情况下，kmap 几乎不需要任何操作(简单的数值计算)，但是在 highmem 下，这个就非常复杂了，因为预留的用于 highmem 映射的空间需要回收，建立页表映射关系，TLB ，还有一些 preemption 的问题
